#Run HTTPD
- name: Run HTTPD
  docker_container:
    name: httpd
    image: kilouatt/httpd:latest
    recreate: true
    pull: true
    ports:
      - "80:80"
    networks:
      - name: app_network

