#Run HTTPD
- name: Run HTTPD
  docker_container:
    name: httpd
    image: kilouatt/httpd:latest
    state: started
    recreate: true
    pull: true
    ports:
      - 81:80
    networks:
      - name: app_network
    env:
      VUE_APP_API_URL: "{{ VUE_APP_API_URL }}"

