#Run Backend
- name: Run Backend
  docker_container:
    name: backend
    image: kilouatt/backend:latest
    env:
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
    networks:
      - name: app_network