#Run Backendd
- name: Run Backend1
  docker_container:
    name: backend1
    image: kilouatt/backend:latest
    recreate: true
    pull: true
    env:
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"

    networks:
      - name: app_network

#Run Backend
- name: Run Backend2
  docker_container:
    name: backend2
    image: kilouatt/backend:latest
    recreate: true
    pull: true
    env:
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"

    networks:
      - name: app_network