#Run Database
- name: Run Database
  docker_container:
    name: database
# We take the good image
    image: kilouatt/database:latest
# We recreate the container every time
    recreate: true
    pull: true
# We take the good environment variables
    env:
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
    networks:
      - name: app_network