#Run Database
- name: Run Database
  docker_container:
    name: database
    image: kilouatt/database:latest
    env:
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
    networks:
      - name: app_network