version: '3.8'

services:
    backend:
        #build: ./Java/api/simple-api-student-main/
        env_file: .env
        networks:
          - app-network
        depends_on:
          - database
        image: kilouatt/backend:1.0

    database:
        #build: ./Database
        volumes:
          - database:/var/lib/postgresql/data
        networks:
          - app-network
        env_file: .env
        image: kilouatt/database:1.0

    httpd:
        #build: ./Http
        ports:
          - 80:80
        networks:
          - app-network
        depends_on:
          - backend
        image: kilouatt/httpd:1.0

networks:
    app-network:


volumes:
    database: