version: '3.8'

services:
    backend:
        build: ./Java/api/simple-api-student-main/
        networks:
          - app-network
        depends_on:
          - database

    database:
        build: ./Database
        volumes:
          - ./Database/data:/var/lib/postgresql/data
        networks:
          - app-network

    httpd:
        build: ./http
        ports:
          - 80:80
        networks:
          - app-network
        depends_on:
          - backend

networks:
    app-network: